### ISSUE TITLE
Handle custom property fields on _bindValue in ElementAdapter and LinkAdapter

### ISSUE THREAD

**Issue by bSm1le** [convergencelabs/jointjs-utils#3]
Find how to handle and bind custom property fields dynamically by cell to have synced data between connected sessions.

After closer inspection I saw that all the required and custom property fields are located in cell.attributes for both element and link cells.
One solution that comes to my mind to have dynamically binded property keys, is to use (for in loop) to get key and build _bindValue with key.

**Comment by mmacfadden** [comment]
This has been fixed.
